default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build

build:
  stage: build
  only:
    - main
  parallel:
    matrix:
      - COMPONENT: [frontend, backend]
  script:
    - docker build -t $CI_REGISTRY/sbibauw/languagelab-$COMPONENT:latest $COMPONENT
    - docker push $CI_REGISTRY/sbibauw/languagelab-$COMPONENT:latest $COMPONENT
