services:
  languagelab-frontend:
    container_name: languagelab-frontend
    image: registry.forge.uclouvain.be/sbibauw/languagelab:frontend
    environment:
      - PUBLIC_API_URL=https://languagelab.be/tmp-api
      - PUBLIC_API_PROXY=https://languagelab.be/tmp-api
      - PUBLIC_APP_URL=https://languagelab.be
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - languagelab-backend
    networks:
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`languagelab.be`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"

  languagelab-backend:
    container_name: languagelab-backend
    image: registry.forge.uclouvain.be/sbibauw/languagelab:backend
    environment:
      - DATABASE_URL=sqlite:////data/db.sqlite3
      - JWT_SECRET_KEY=${LANGUAGELAB_JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${LANGUAGELAB_JWT_REFRESH_SECRET_KEY}
      - ADMIN_EMAIL=${LANGUAGELAB_ADMIN_EMAIL}
      - ADMIN_PASSWORD=${LANGUAGELAB_ADMIN_PASSWORD}
      - CALCOM_SECRET=${LANGUAGELAB_CALCOM_SECRET}
      - ALLOWED_ORIGINS=https://languagelab.be,https://api.languagelab.be
    volumes:
      - /mnt/data/languagelab/backend:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend.rule=Host(`languagelab.be`) && (PathPrefix(`/tmp-api`) || PathPrefix(`/docs`) || PathPrefix(`/openapi.json`))"

  languagelab-frontend-dev:
    container_name: languagelab-frontend-dev
    image: registry.forge.uclouvain.be/sbibauw/languagelab:frontend-dev
    environment:
      - PUBLIC_API_URL=https://dev.languagelab.be/tmp-api
      - PUBLIC_API_PROXY=https://dev.languagelab.be/tmp-api
      - PUBLIC_APP_URL=https://dev.languagelab.be
      - PUBLIC_WS_URL=wss://dev.languagelab.be/tmp-api/v1/ws
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - languagelab-backend-dev
    networks:
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-dev.rule=Host(`dev.languagelab.be`)"
      - "traefik.http.routers.frontend-dev.tls=true"
      - "traefik.http.services.frontend-dev.loadbalancer.server.port=8080"

  languagelab-backend-dev:
    container_name: languagelab-backend-dev
    image: registry.forge.uclouvain.be/sbibauw/languagelab:backend-dev
    environment:
      - DATABASE_URL=sqlite:////data/db.dev.sqlite3
      - JWT_SECRET_KEY=${LANGUAGELAB_JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${LANGUAGELAB_JWT_REFRESH_SECRET_KEY}
      - ADMIN_EMAIL=${LANGUAGELAB_ADMIN_EMAIL}
      - ADMIN_PASSWORD=${LANGUAGELAB_ADMIN_PASSWORD}
      - CALCOM_SECRET=${LANGUAGELAB_CALCOM_SECRET}
      - ALLOWED_ORIGINS=https://dev.languagelab.be,https://api.dev.languagelab.be
    volumes:
      - /mnt/data/languagelab/backend:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-dev.tls=true"
      - "traefik.http.services.backend-dev.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend-dev.rule=Host(`dev.languagelab.be`) && (PathPrefix(`/tmp-api`) || PathPrefix(`/docs`) || PathPrefix(`/openapi.json`))"

  traefik:
    container_name: traefik
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=external"
      - "--entrypoints.external.address=:80"
      - "--entrypoints.externalsecure.address=:443"
      - "--entrypoints.external.http.redirections.entryPoint.to=externalsecure"
      - "--entrypoints.external.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.external.http.redirections.entryPoint.permanent=true"
      - "--providers.file.filename=/etc/traefik/dynamic-config.yaml"
    environment:
      - TZ=Europe/Paris
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: bind
        source: /mnt/data/languagelab/repo/configs/traefik.yaml
        target: /etc/traefik/dynamic-config.yaml
      - type: bind
        source: /mnt/data/languagelab/repo/configs/languagelab_be.key
        target: /etc/traefik/languagelab_be.key
      - type: bind
        source: /mnt/data/languagelab/repo/configs/languagelab_be.pem
        target: /etc/traefik/languagelab_be.pem
    restart: always
    networks:
      - external

networks:
  external:
