services:
  languagelab-frontend:
    container_name: languagelab-frontend
    build: frontend
    ports:
      - 8080:80
    depends_on:
      - languagelab-backend

  languagelab-backend:
    container_name: languagelab-backend
    build: backend
    ports:
      - 8000:8000
