services:
  languagelab-frontend:
    container_name: languagelab-frontend
    image: registry.forge.uclouvain.be/sbibauw/languagelab:frontend
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - languagelab-backend
    networks:
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`languagelab.sipr.ucl.ac.be`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"

  languagelab-backend:
    container_name: languagelab-backend
    image: registry.forge.uclouvain.be/sbibauw/languagelab:backend
    environment:
      - DATABASE_URL=sqlite:////data/db.sqlite3
      - JWT_SECRET_KEY=${LANGUAGELAB_JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${LANGUAGELAB_JWT_REFRESH_SECRET_KEY}
      - ADMIN_EMAIL=${LANGUAGELAB_ADMIN_EMAIL}
      - ADMIN_PASSWORD=${LANGUAGELAB_ADMIN_PASSWORD}
      - CALCOM_SECRET=${LANGUAGELAB_CALCOM_SECRET}
      - ALLOWED_ORIGINS=http://languagelab.sipr.ucl.ac.be
    volumes:
      - /mnt/data/languagelab/backend:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`languagelab.sipr.ucl.ac.be`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  traefik:
    container_name: traefik
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=external"
      - "--entrypoints.internal.address=:80"
    environment:
      - TZ=Europe/Paris
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - external

networks:
  external:
